### ISSUE TITLE
Differences between scriptTemplate.sh and simpleScriptTemplate.sh ?

### ISSUE THREAD

**Issue by mtx-z** [natelandau/shell-scripts#2]
Hello there.

Thanks for those templates !
I'm wandering what are the differences between scriptTemplate.sh and simpleScriptTemplate.sh ?

I dont see anything in the readme about simpleScriptTemplate.sh.

Thanks !

**Comment by pascalandy** [comment]
Same question !

**Comment by natelandau** [comment]
no longer relevant
